### PR TITLE
Remove get-earn-protocol-* lambdas

### PR DESCRIPTION
**Pull request by marcinciarka**
Remove get-earn-protocol-* lambdas

## Summary by CodeRabbit

- **Chores**
	- Removed the `addEarnProtocolConfig` function and its references from the project, indicating the Earn Protocol configuration is no longer part of the stack setup.
	- Deleted multiple configuration files including `package.json`, `Dockerfile`, and various TypeScript and ESLint configurations, which may impact the build and deployment processes.
	- Removed GraphQL queries related to fleet and portfolio details, which may affect data retrieval capabilities for users interacting with the Earn Protocol.

### CODE REVIEW

**Comment by marcinciarka** [comment]
@coderabbitai pause

**Comment by piotrwitek** [comment]
Added [Added GetVaultsRaw, GetVaultRaw methods to the sdk](https://github.com/OasisDEX/summerfi-monorepo/pull/545/commits/464c43b56718ac6c011aecc19259808e350a30ac)

**Review by piotrwitek — APPROVED** [review]
Looks good

**Comment by piotrwitek** [comment]
Added usage examples and tests:
```
it('should getVaults', async () => {
  const raw = await sdk.armada.users.getVaultsRaw({
    chainInfo,
  })
  expect(raw.vaults).toHaveLength(1)
  expect(raw.vaults[0]?.id).toEqual(`${fleetAddress.value}`)
})

it('should getVault', async () => {
  const raw = await sdk.armada.users.getVaultRaw({
    poolId: ArmadaVaultId.createFrom({
      chainInfo,
      fleetAddress,
    }),
  })
expect(raw.vault?.id).toEqual(`${fleetAddress.value}`)
  ```

**Review by piotrwitek — APPROVED** [review]
Approved :)

**Pull request merged**
